name: Build and Run Go Program

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Go environment
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.19'

      # Step 3: Build Go program
      - name: Build Go program
        run: |
          go build hello.go

      # Step 4: Run Go program
      - name: Run Go program
        run: |
          ./hello

  golangci-lint:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Go environment
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.19'

      # Step 3: Install GolangCI-Lint
      - name: Install GolangCI-Lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s v1.50.1
          sudo mv ./bin/golangci-lint /usr/local/bin/

      # Step 4: Run GolangCI-Lint
      - name: Run GolangCI-Lint
        run: golangci-lint run