name: Build and Run Go Program

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

jobs2:
      golangci-lint:
        runs-on: ubuntu-latest
    
        steps:
          # Step 1: Checkout the code
          - name: Checkout code
            uses: actions/checkout@v2
    
          # Step 2: Set up Go environment
          - name: Set up Go
            uses: actions/setup-go@v2
            with:
              go-version: '1.17'  

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.19'

      - name: Build Go program
        run: |
          go build hello.go

      - name: Run Go program
        run: |
          ./hello
